### ISSUE TITLE
How about this?

### ISSUE THREAD

**Issue by Tamota** [Tamota/Hello-World#1]
![hello_world](https://cloud.githubusercontent.com/assets/29059450/26752208/734e91b6-4842-11e7-9be6-20f78f8c5ac3.gif)

**Comment by mayokek** [comment]
Looks good to me

**Comment by Tamota** [comment]
Haha XD its for the README

**Comment by FoxIshDaBest** [comment]
fje

**Comment by Tamota** [comment]
mhm
